# Generated by Django 5.1.4 on 2024-12-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_chai_certificate_chai_review_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chai_certificate',
            name='certificate',
        ),
    ]
